id: P191F2183
initial_creation_type: ocr
source_metadata:
  volumes:
    ca3ed7acba424240aab552b310b7f022:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: རྣམ་འཇོམས་ཀྱི་སྒྲུབ་ཐབས་བརྒྱ་རྩ་བརྒྱད།
      total_pages: 1125
      volume_number: 38
vol2fn:
  v038: v038.txt